### ISSUE TITLE
Bug found related to bouncerTimeout

### ISSUE THREAD

**Issue by Madriix** [freenode/jbnc#85]
In production, the bouncerTimeout is set to 5400, which equals 90 minutes. Today, I connected to IRC with Jbnc and noticed that it disconnected at 17:09, even though I was still connected to IRC with JBNC. I had been connected since 15:40. This is the second time this bug has occurred this month, but it may happen more often without me noticing.

Where could the issue be coming from?

**Comment by realrasengan** [comment]
It means it thinks no clients are connected... not a good thing if you're actually connected!

**Comment by Madriix** [comment]
@realrasengan I think I now know how to reproduce the bug. It might require the following steps:

1. Connect to IRC with JBNC (using device 1) and leave it connected.
2. Use another device, connect (and maybe set yourself as away or trigger away mode, then come back and let it go away again).
3. After this, it seems that JBNC shuts down abruptly after 1 hour and 30 minutes, which is the duration of the bouncerTimeout.

I haven't tested it with a lower value, like 1 minute, but I will. JBNC shuts down suddenly and doesn’t stop the way it usually should.

**Comment by Madriix** [comment]
I just tested this locally; here is the test.

Requirements:
- Have 3 IRC clients open
- The first one is logged in to JBNC (client-1)
- The second is also a client connected to JBNC using the same PASS (client-2)
- The third client (client-3) is, for example, an Ircop or any client that can send messages in a test channel for the Login user to read on JBNC. It is not connected to JBNC.

Here is the test:
1. Connect to JBNC with client-1.
2. Using client-3 (e.g., Not JBNC), write "test1" in the channel. It is successfully received on client-1, and the message is visible.
3. Connect to JBNC with client-2.
4. Using client-3 (e.g., Not JBNC), write "test2" in the channel. It is successfully received on both client-1 and client-2, and the message is visible.
5. Disconnect client-2 from JBNC with a simple "/quit".
6. Using client-3 (e.g., Not JBNC), write "test3" in the channel. Client-1 does not receive it. No further messages are received. Now I test with a PM, and it is not received either. However, JBNC remains connected to IRC, it seems it stays connected, and the `bouncerTimeout` has no effect. The client is not marked as away either.

Where could the issue come from? This is problematic, as it can affect regular users (99%) who reconnect to their JBNC client, first with one device, then later with another, such as a computer and a smartphone. Bad for UX.

**Comment by Madriix** [comment]
I have updated: https://github.com/freenode/jbnc/pull/86 and I am currently testing it in production.
